version: '3.7'
services:
  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    volumes: 
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "Jaquelina00"
      MYSQL_DATABASE: wasd_copyshop

  server:
    build: ../wasd_copyshop-backend
    container_name: server
    restart: on-failure
    volumes:
      - ../wasd_copyshop-backend:/usr/src/service/server
      - /usr/src/service/server/node_modules
    working_dir: /usr/src/service/server
    hostname: api
    environment:
      HOST: 127.0.0.1
      PORT : 5000
      JWT_PRIVATY_KEY : MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgiyvo0X+VQ0yIrOaNnlrnUclopnvuuMfoc8HHly3505OhRANCAAQWUcdZ8uTSAsFuwtNy4KtsKqgeqYxg
      ADMIN_EMAIL : wasd_admin@admin.com
      ADMIN_PASSWORD : admin
      DB_USER : root
      DB_PASSWORD : Jaquelina00
      DB_HOST : db_mysql
      DB_PORT : 3306
    command: 'yarn start'

  reactapp:
    build: ../wasd_copyshop-frontend
    restart: on-failure
    container_name: reactapp
    working_dir: /reactapp
    hostname: client
    volumes:
      - ../wasd_copyshop-frontend:/reactapp
      - /reactapp/node_modules
    ports:
      - "80:8080"

volumes:
  db:
    driver: local